spring:

  application:
    name: competition_training_system


  datasource:
    url: jdbc:mysql://localhost:3306/competition_training_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB





#Mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: learning-javaweb0
    region: cn-hangzhou

server:
  port: 8000
